package io.eduonline.devrush.devrushlmsmultiplatform.theme

data class Strings(
    val january: String,
    val february: String,
    val march: String,
    val april: String,
    val may: String,
    val june: String,
    val july: String,
    val august: String,
    val september: String,
    val october: String,
    val november: String,
    val december: String,

    val bottomCourses: String,
    val bottomLibraries: String,
    val bottomChat: String,
    val bottomProfile: String,

    val globalEmptyStateText: String,

    val screenNameCourseInfo: String,
    val screenNameLibraryInfo: String,

    val courseInfoModule: String,
    val courseInfoModuleUnavailable: String,
    val courseInfoActionResume: String,
    val courseInfoTabsBasic: String,
    val courseInfoTabsCourseProgram: String,
    val courseInfoReviews: String,
    val courseInfoCertificate: String,
    val courseInfoUntitled: String,

    val courseLessonMissing: String,
    val courseLessonLoading: String,
    val courseLessonFilesForLesson: String,
    val courseLessonFileDownloading: String,
    val courseLessonFileDownloaded: String,
    val courseLessonFileNotDownloaded: String,

    val devrushCommunity: String,

    val urPath: String,

    val libraryTitle: String,

    val authorizationTitle: String,
    val authorizationEnterYourEmail: String,
    val authorizationEnterYourEmailPlaceholder: String,
    val authorizationPassword: String,
    val authorizationPasswordPlaceholder: String,
    val authorizationEnterButton: String,
    val authorizationForgotPassword: String,
    val authorizationWordBetweenDivider: String,
    val authorizationEnterByOtherService: String,
    val authorizationNoAccount: String,
    val authorizationButtonToRegistration: String,
    val authorizationErrorTextField: String,
    val authorizationErrorLoginTextField: String,
    val authorizationErrorLoginEmptyTexField: String,
    val authorizationErrorPasswordMinTextField: String,
    val authorizationErrorPasswordMaxTextField: String,
    val authorizationErrorPasswordEmptyTextField: String,
    val authorizationNoInternet: String,


    val registrationTitle: String,
    val registrationName: String,
    val registrationNamePlaceholder: String,
    val registrationPasswordTitle: String,
    val registrationConfirmPasswordTitle: String,
    val registrationEmailTitle: String,
    val registrationEmailPlaceholder: String,
    val registrationIsErrorEmail: String,
    val registrationIsErrorConfirmPassword: String,
    val registrationEnterReg: String,
    val registrationEnterTitleRules: String,
    val registrationConfidentiality: String,
    val registrationAnd: String,
    val registrationServerRules: String,
    val registrationTitleAuthorization: String,
    val registrationEnterAuthorization: String,
    val registrationEnterWe: String,
    val registrationPolicy: String,
    val registrationIsErrorName: String,
    val registrationIsErrorMinLengthPassword: String,
    val registrationIsErrorMaxLengthPassword: String,

    val forgetPasswordTitle: String,
    val forgetPasswordEnterYourEmail: String,
    val forgetPasswordEnterYourEmailPlaceholder: String,
    val forgetPasswordDontExist: String,
    val forgetPasswordSend: String,
    val forgetPasswordEmptyError: String,
    val forgetPasswordInvalidEmail: String,
    val forgotSuccessSend: String,

    val onboardingStart: String,
    val onboardingNext: String,
    val onboardingSkip: String,
    val onboardingScreen1Title: String,
    val onboardingScreen1Description: String,
    val onboardingScreen2Title: String,
    val onboardingScreen2Description: String,
    val onboardingScreen3Title: String,
    val onboardingScreen3Description: String,
    val onboardingScreen4Title: String,
    val onboardingScreen4Description: String,


    val quizAboutUrSelf: String,
    val quizProgrammingLanguage: String,
    val quizAnswerAFewQuestions: String,

    val swift: String,
    val kotlin: String,

    val quizJavascript: String,
    val quizChooseFramework: String,
    val quizUiKit: String,
    val quizNodeJs: String,
    val quizReact: String,
    val quizSwiftUI: String,
    val quizContinue: String,
    val quizBack: String,
    val quizHowLongLearn: String,
    val quizSixMonth: String,
    val quizMoreSixMonth: String,
    val quizYear: String,
    val quizUrInterests: String,
    val quizPainting: String,
    val quizMusic: String,
    val quizFashion: String,
    val quizCinema: String,
    val quizExhibitions: String,
    val quizArt: String,
    val quizVocals: String,
    val quizQuests: String,
    val quizSport: String,
    val quizDance: String,
    val quizEnd: String,

    val couponFully: String,
    val couponCourse: String,
    val coupon15: String,
    val couponLucky: String,
    val couponSwipe: String,
    val couponSignUp: String,
    val couponSkidka15: String,

    val listOfCoursesCourses: String,
    val listOfCoursesCat: String,
    val listOfCoursesStartedCourses: String,
    val listOfCourses: String,
    val listOfCoursesNotifications: String,
    val listOfCoursesMarkAll: String,
    val listOfCoursesAccrual: String,
    val listOfCoursesSum: String,
    val listOfCoursesLink: String,
    val listOfCoursesReferral: String,

    val coursesStart: String,
    val all: String,

    val profileDescription: String,
    val profileBestProject: String,
    val profileBestProjectDescription: String,
    val profileActiveAchievements: String,
    val profileAllAchievements: String,
    val profileInactiveAchievements: String,
    val profileHero: String,
    val profileMentor: String,
    val profileMentorPro: String,
    val profileTop5: String,
    val profileBestReport: String,
    val profile: String,
    val profileMyStatistics: String,
    val profilePoints: String,
    val profileRank: String,
    val profileAchievements: String,
    val profileLeader: String,
    val profileReporter: String,
    val profileResearcher: String,
    val profileLeaderboard: String,
    val profileFirstPlace: String,
    val profileSecondPlace: String,
    val profileThirdPlace: String,
    val profileAccessPayments: String,
    val profileSubscriptions: String,
    val profileAccesses: String,
    val profileOrders: String,
    val profileOrder: String,
    val profileSettings: String,
    val profileDone: String,
    val profileChangePhoto: String,
    val profileAccount: String,
    val profileEmail: String,
    val profileName: String,
    val profileSurname: String,
    val profilePatronymic: String,
    val profilePhone: String,
    val profileBirthDate: String,
    val profileGender: String,
    val profileGenderMale: String,
    val profileGenderFemale: String,
    val profilePasswordSettings: String,
    val profilePassword: String,
    val profileConfirmPassword: String,
    val profileAppSettings: String,
    val profileNewsUpdatesPromotions: String,
    val profileTheme: String,
    val profileDarkTheme: String,
    val profileLightTheme: String,
    val profileSystemTheme: String,
    val profileLogout: String,
    val profileDeleteAccount: String,
    val profileCat: String,
    val profileCourse: String,
    val profileLibrary: String,
    val profileActive: String,
    val profileExpired: String,
    val profileCreationDate: String,
    val profileExpires: String,
    val profileRenewSubscription: String,
    val profileCancelSubscription: String,
    val profileOrderAmount: String,
    val profileDateOfDebiting: String,
    val profilePayOrder: String,
    val profileNotSavedProfile: String,
    val profileEmptyLeaderboard: String,
    val profileAmountOfPayment: String,
    val profileCancelSubscriptionRenewal: String,
    val profileRenewalIsSuspended: String,
    val profileConfirmSnackBar: String,
    val profileSuccessChangeData: String,
    val profileEmptyName: String,
    val profileSettingsPhoneTextFieldValidationError: String,
    val profileSettingsPhoneTextFieldSelectCountry: String,
    val profileDatePickerOk: String,
    val profileDatePicketCancel: String,

    val accessesPaymentsUnlimitedAccess: String,
    val accessesPaymentsEmptyPlug: String,

    val coursesCourses: String,
    val coursesStartedCourses: String,
    val coursesListCourses: String,
    val coursesSearch: String,
    val coursesFilterAll: String,

    val chatMessageRemoved: String,
    val chatYouDeletedThisMessage: String,
    val chatAnswer: String,
    val chatPhoto: String,

    val notificationStudentPartnershipRegistration: String,
    val notificationStudentPartnershipTransaction: String,
    val notificationPasswordChanged: String,
    val notificationStudentBonusTransaction: String,
    val notificationLibraryItemComment: String,
    val notificationStudentBonus: String,
    val notificationDeposit: String,
    val notificationWithdrawal: String,
    val notificationAdminPartnershipTransactionRequest: String,
    val notificationCourseTaskAnswerStatus: String,
    val notificationTaskInStep: String,
    val notificationApproved: String,
    val notificationNeedAdd: String,
)

val russian = Strings(
    january = "Января",
    february = "Февраля",
    march = "Марта",
    april = "Апреля",
    may = "Майя",
    june = "Июня",
    july = "Июля",
    august = "Августа",
    september = "Сентября",
    october = "Октября",
    november = "Ноября",
    december = "Декабря",

    bottomCourses = "Курсы",
    bottomLibraries = "Библиотеки",
    bottomChat = "Чат",
    bottomProfile = "Профиль",

    globalEmptyStateText = "Тут ничего нет \n Зато есть милый котик :)",

    screenNameCourseInfo = "О курсе",
    screenNameLibraryInfo = "О библиотеке",

    courseInfoModule = "Модуль",
    courseInfoModuleUnavailable = "Недоступен",
    courseInfoActionResume = "Продолжить",
    courseInfoTabsBasic = "Основное",
    courseInfoTabsCourseProgram = "Программа курса",
    courseInfoReviews = "Отзывы",
    courseInfoCertificate = "Сертификат об окончании",
    courseInfoUntitled = "Без названия",

    courseLessonMissing = "Файлы отсутствуют",
    courseLessonLoading = "Загрузка...",
    courseLessonFilesForLesson = "Файлы к уроку",
    courseLessonFileDownloading = "Файл загружается",
    courseLessonFileDownloaded = "Файл загружен",
    courseLessonFileNotDownloaded = "Не удалось загрузить файл",

    libraryTitle = "Библиотека",

    devrushCommunity = "Devrush Community",

    urPath = "Это твой практический путь в мир программирования.",

    authorizationTitle = "Вход",
    authorizationEnterYourEmail = "Введите почту",
    authorizationEnterYourEmailPlaceholder = "mail@mail.ru",
    authorizationPassword = "Пароль",
    authorizationPasswordPlaceholder = "Пароль",
    authorizationEnterButton = "Войти",
    authorizationForgotPassword = "Забыли пароль?",
    authorizationWordBetweenDivider = "или",
    authorizationEnterByOtherService = "Войти через Google",
    authorizationNoAccount = "У вас еще нет аккаунта? ",
    authorizationButtonToRegistration = "Зарегистрироваться",
    authorizationErrorTextField = "Неверные логин или пароль",
    authorizationErrorLoginTextField = "Неверный email. Разрешены только цифры и латинские буквы.",
    authorizationErrorLoginEmptyTexField = "Обязательное поле",
    authorizationErrorPasswordMinTextField = "Пароль должен быть длиннее 6 символов",
    authorizationErrorPasswordMaxTextField = "Пароль должен быть короче 30 символов",
    authorizationErrorPasswordEmptyTextField = "Пожалуйста, введите ваш пароль.",
    authorizationNoInternet = "Нет соединения с интернетом",

    registrationTitle = "Регистрация",
    registrationName = "Ваше Имя",
    registrationNamePlaceholder = "Имя",
    registrationEmailTitle = "Введите почту",
    registrationConfirmPasswordTitle = "Подтвердите пароль",
    registrationPasswordTitle = "Пароль",
    registrationEmailPlaceholder = "mail@mail.ru",
    registrationIsErrorEmail = "Некоретная почта",
    registrationIsErrorConfirmPassword = "Пароли не совпадают",
    registrationIsErrorName = "Обязательное поле",
    registrationEnterReg = "Зарегистрироватся",
    registrationEnterTitleRules = "Нажимая продолжить вы соглашаетесть с ",
    registrationConfidentiality = "политикой конфиденциальности",
    registrationAnd = " и ",
    registrationServerRules = "правилами сервиса",
    registrationIsErrorMinLengthPassword = "Пароль должен быть длиннее 6 символов",
    registrationIsErrorMaxLengthPassword = "Пароль должен быть короче 30 символов",
    registrationTitleAuthorization = "У вас есть аккаунт? ",
    registrationEnterAuthorization = "Войти",
    registrationEnterWe = "Мы очень рады, что ты присоединился к нам. Чтобы обеспечить комфортную и продуктивную обстановку для всех участников, просим тебя ознакомиться с некоторыми правилами нашего сервера:\n" +
            "\n" +
            "Запрещено: использование нецензурной речи в чате, публикация материалов 18+, обсуждение политики. \uD83D\uDEAB\n" +
            "\n" +
            "Это важно не только для поддержания положительного эмоционального состояния всего комьюнити, но и для того, чтобы Discord не забанил вас и не накинул нам на сервер страйк.\uD83E\uDD10\n" +
            "\n" +
            "В целом, у нас дружелюбное и адекватное комьюнити, где нет хейта и разных \"подколок\".\n" +
            "\n" +
            "Мы не приветствуем негатив.\n" +
            "\n" +
            "У нас не просто бокал всегда на половину полон, он на половину полон самым дорогим вином, и мы готовы им делиться . \uD83C\uDF77\uD83D\uDE0E\n" +
            "\n" +
            "Каждый участник готов прийти на помощь другому.\uD83E\uDEC2\n" +
            "\n" +
            "Вступая в наше комьюнити, вы берёте на себя ответственность за своё обучение, никто не будет вас насильно тянуть. \uD83D\uDE4C",
    registrationPolicy = "Политика конфиденциальности\n" +
            "\n" +
            "Эта политика конфиденциальности описывает, какие данные мы собираем, для чего они используются и как мы их защищаем в нашем приложении.\n" +
            "\n" +
            "Собираемые данные:\n" +
            "Мы собираем следующие данные от пользователей:\n" +
            "Имя и адрес электронной почты для регистрации\n" +
            "Данные о местоположении при использовании геолокации\n" +
            "Информацию об устройстве (тип устройства, версия операционной системы и др.)\n" +
            "Использование данных:\n" +
            "Собранные данные используются исключительно для:\n" +
            "Предоставления пользователю возможности пользоваться функционалом приложения\n" +
            "Обратной связи с пользователем\n" +
            "Улучшения качества предоставляемых услуг\n" +
            "Защита данных:\n" +
            "Мы принимаем меры для защиты данных пользователей от несанкционированного доступа, утечек или утраты. Мы не передаем данные третьим лицам без вашего согласия.\n" +
            "\n" +
            "Согласие пользователя:\n" +
            "Используя наше приложение, вы соглашаетесь с нашей политикой конфиденциальности. Если у вас есть какие-либо вопросы или требуется дополнительная информация, свяжитесь с нами.\n" +
            "\n" +
            "Данная политика конфиденциальности вступает в силу с момента использования приложения пользователями. Любые изменения в политике будут опубликованы на этой странице.\n" +
            "\n",
    forgetPasswordTitle = "Забыли пароль?",
    forgetPasswordEnterYourEmail = "Введите почту",
    forgetPasswordEnterYourEmailPlaceholder = "mail@mail.ru",
    forgetPasswordDontExist = "Профиля с такой почтой не существует",
    forgetPasswordEmptyError = "Обязательное поле",
    forgetPasswordInvalidEmail = "Неверный email. Разрешены только цифры и латинские буквы.",
    forgotSuccessSend = "Сообщение было отправлено на почту" +
            "\nСледуйте инструкциям в письме, чтобы завершить настройку учетной записи.",
    forgetPasswordSend = "Отправить",

    onboardingStart = "Начать",
    onboardingNext = "Дальше",
    onboardingSkip = "Пропустить",
    onboardingScreen1Title = "Devrush Community",
    onboardingScreen1Description = "Твой практический путь в мир разработки",
    onboardingScreen2Title = "Команда",
    onboardingScreen2Description = "Научись работать в команде, участвуя в командной разработке, приближенной к коммерческой.",
    onboardingScreen3Title = "Портфолио",
    onboardingScreen3Description = "Проходи наши обучающие программы и добавь минимум 12 работающих приложений в своё портфолио.",
    onboardingScreen4Title = "База знаний",
    onboardingScreen4Description = "За два года существования нашего сообщества мы собрали для вас большую базу знаний по изучению программирования.",

    quizAboutUrSelf = "Расскажите о себе",
    quizProgrammingLanguage = "Какой язык программирования вы планируете изучать?",
    quizAnswerAFewQuestions = "Ответьте на несколько вопросов. И получите в конце БОНУС!",

    swift = "Swift",
    kotlin = "Kotlin",

    quizJavascript = "JavaScript",
    quizChooseFramework = "Выберите фреймворк?",
    quizUiKit = "UIKit",
    quizNodeJs = "Node JS",
    quizReact = "React",
    quizSwiftUI = "Swift UI",
    quizContinue = "Продолжить",
    quizBack = "Назад",
    quizHowLongLearn = "Как давно вы изучаете данный язык программирования?",
    quizSixMonth = "< 6 месяцев",
    quizMoreSixMonth = "> 6 месяцев",
    quizYear = "> 1 года",
    quizUrInterests = "Ваши интересы",
    quizPainting = "Живопись",
    quizMusic = "Музыка",
    quizFashion = "Мода",
    quizCinema = "Кино",
    quizExhibitions = "Выставки",
    quizArt = "Искусство",
    quizVocals = "Вокал",
    quizQuests = "Квесты",
    quizSport = "Спорт",
    quizDance = "Танцы",
    quizEnd = "Завершить",

    couponFully = "От корки до корки",
    couponCourse = "Вам подходит курс “Пруст, Камю и Сартр: как понять французскую литературу",
    coupon15 = "Мы дарим вам промокод со скидкой 15% на данный курс",
    couponLucky = "Попытать удачу",
    couponSwipe = "Проведите чтобы оторвать билет",
    couponSignUp = "Записаться на курс",
    couponSkidka15 = "SKIDKA15",

    listOfCoursesCourses = "Курсы",
    listOfCoursesCat = "Зато есть милый котик :)",
    listOfCoursesStartedCourses = "Начатые курсы",
    listOfCourses = "Список курсов",
    listOfCoursesNotifications = "Уведомления",
    listOfCoursesMarkAll = "Отметить все как прочитанное",
    listOfCoursesAccrual = "Начисление по партнерской программе",
    listOfCoursesSum = "Сумма",
    listOfCoursesLink = "Ссылка",
    listOfCoursesReferral = "Реферал",

    coursesStart = "Начать",
    all = "Все",

    profileDescription = "Описание",
    profileBestProject = "Лучший командный проект",
    profileBestProjectDescription = "Проект сделанный на командном челлендже был выбран лучшим среди всех команд",
    profileActiveAchievements = "Активные достижения",
    profileAllAchievements = "Все достижения",
    profileInactiveAchievements = "Не активные достижения",
    profileHero = "Кино - Герой",
    profileMentor = "Mentor",
    profileMentorPro = "Mentor PRO",
    profileTop5 = "TOP 5",
    profileBestReport = "Лучший доклад",
    profile = "Профиль",
    profileMyStatistics = "Моя статистика",
    profilePoints = "Баллы",
    profileRank = "Место",
    profileAchievements = "Достижения",
    profileLeader = "Командный лидер",
    profileReporter = "Докладчик",
    profileResearcher = "Ученик исследователь",
    profileLeaderboard = "Таблица лидеров",
    profileFirstPlace = "1 место",
    profileSecondPlace = "2 место",
    profileThirdPlace = "3 место",
    profileAccessPayments = "Доступы и оплаты",
    profileSubscriptions = "Подписки",
    profileAccesses = "Доступы",
    profileOrders = "Заказы",
    profileOrder = "Заказ",
    profileSettings = "Настройки профиля",
    profileDone = "Готово",
    profileChangePhoto = "Изменить фото профиля",
    profileAccount = "Аккаунт",
    profileEmail = "Почта",
    profileName = "Имя",
    profileSurname = "Фамилия",
    profilePatronymic = "Отчество",
    profilePhone = "Телефон",
    profileBirthDate = "День рождения",
    profileGender = "Пол",
    profileGenderFemale = "Женский",
    profileGenderMale = "Мужской",
    profilePasswordSettings = "Настройки пароля",
    profilePassword = "Пароль",
    profileConfirmPassword = "Подтвердите пароль",
    profileAppSettings = "Настройки приложения",
    profileNewsUpdatesPromotions = "Новости, анонсы, акции",
    profileTheme = "Тема",
    profileDarkTheme = "Темная",
    profileLightTheme = "Светлая",
    profileSystemTheme = "Системная",
    profileLogout = "Выйти",
    profileDeleteAccount = "Удалить аккаунт",
    profileCat = "Тут ничего нет. Зато есть милый котик ;)",
    profileCourse = "Курс",
    profileLibrary = "Библиотека",
    profileActive = "Активные",
    profileExpired = "Истекшие",
    profileCreationDate = "Дата создания",
    profileExpires = "Истекает",
    profileNotSavedProfile = "Аккуратнее, вы не сохранили изменения!",
    profileRenewSubscription = "Продлить подписку",
    profileCancelSubscription = "Отменить подписку",
    profileCancelSubscriptionRenewal = "Отменить продление",
    profileOrderAmount = "Сумма заказа",
    profilePayOrder = "Оплатить",
    profileDateOfDebiting = "Дата списания",
    profileEmptyLeaderboard = "Таблица лидеров пуста",
    profileAmountOfPayment = "Сумма платежа",
    profileRenewalIsSuspended = "Продление приостановленно",
    profileConfirmSnackBar = "Пароли должны совпадать",
    profileSuccessChangeData = "Данные успешно изменены",
    profileEmptyName = "Заполните обязательные поля",
    profileSettingsPhoneTextFieldValidationError = "Введите валидный номер телефона",
    profileSettingsPhoneTextFieldSelectCountry = "Выберите страну",
    profileDatePicketCancel = "Отменить",
    profileDatePickerOk = "Принять",

    accessesPaymentsUnlimitedAccess = "Неограниченный доступ",
    accessesPaymentsEmptyPlug = "В настоящий момент здесь ничего нет :)",

    coursesCourses = "Курсы",
    coursesStartedCourses = "Начатые курсы",
    coursesListCourses = "Список курсов",
    coursesSearch = "Поиск",
    coursesFilterAll = "Все",
    chatMessageRemoved = "Сообщение удалено",
    chatYouDeletedThisMessage = "Вы удалили данное сообщение",
    chatAnswer = "Ответ",
    chatPhoto = "Фото",

    notificationStudentPartnershipRegistration = "Новая регистрация реферала",
    notificationStudentPartnershipTransaction = "Начисление по партнерской программе",
    notificationPasswordChanged = "Ваш пароль был изменен. Если это сделали не вы, то обратитесь в техподдержку",
    notificationStudentBonusTransaction = "Списание с бонусного счета",
    notificationLibraryItemComment = "Комментарий к шагу библиотеки",
    notificationStudentBonus = "Начисление на бонусный счет",
    notificationDeposit = "Начисление на бонусный счет",
    notificationWithdrawal = "Списание с бонусного счета",
    notificationAdminPartnershipTransactionRequest = "Запрос на вывод по партнерской программе",
    notificationCourseTaskAnswerStatus = "Ответ на задание",
    notificationTaskInStep = "Задание в шаге",
    notificationApproved = "одобрено в курсе",
    notificationNeedAdd = "нужно дополнить в курсе",
)

val english = Strings(
    january = "January",
    february = "February",
    march = "March",
    april = "April",
    may = "May",
    june = "June",
    july = "July",
    august = "August",
    september = "September",
    october = "October",
    november = "November",
    december = "December",

    bottomCourses = "Courses",
    bottomLibraries = "Libraries",
    bottomChat = "Chat",
    bottomProfile = "Profile",

    globalEmptyStateText = "There's nothing here \n But there is a cute cat :)",

    screenNameCourseInfo = "About course",
    screenNameLibraryInfo = "About library",

    courseInfoModule = "Module",
    courseInfoModuleUnavailable = "Unavailable",
    courseInfoActionResume = "Continue",
    courseInfoTabsBasic = "Basic",
    courseInfoTabsCourseProgram = "Course program",
    courseInfoReviews = "Reviews",
    courseInfoCertificate = "Certificate of completion",
    courseInfoUntitled = "Untitled",

    courseLessonMissing = "Files are missing",
    courseLessonLoading = "Loading...",
    courseLessonFilesForLesson = "Files for the lesson",
    courseLessonFileDownloading = "The file is being uploaded",
    courseLessonFileDownloaded = "The file is uploaded",
    courseLessonFileNotDownloaded = "Failed to upload a file",

    devrushCommunity = "Devrush Community",

    urPath = "This is your practical path to the world of programming.",

    authorizationTitle = "Log In",
    authorizationEnterYourEmail = "Enter your email",
    authorizationEnterYourEmailPlaceholder = "mail@mail.ru",
    authorizationPassword = "Password",
    authorizationPasswordPlaceholder = "Password",
    authorizationEnterButton = "Log In",
    authorizationForgotPassword = "Forgot your password?",
    authorizationWordBetweenDivider = "or",
    authorizationEnterByOtherService = "Log in via Google",
    authorizationNoAccount = "Don't you have an account yet? ",
    authorizationButtonToRegistration = "Register",
    authorizationErrorTextField = "Invalid username or password",
    authorizationErrorLoginTextField = "Invalid email. Only numbers and Latin letters are allowed.",
    authorizationErrorLoginEmptyTexField = "required field",
    authorizationErrorPasswordMinTextField = "Password must be longer than 6 characters",
    authorizationErrorPasswordMaxTextField = "The password must be shorter than 30 characters",
    authorizationErrorPasswordEmptyTextField = "Please enter your password",
    authorizationNoInternet = "No internet connection",


    registrationTitle = "Registration",
    registrationName = "Your name",
    registrationNamePlaceholder = "Name",
    registrationIsErrorEmail = "Incorrect email",
    registrationIsErrorConfirmPassword = "Passwords don't match",
    registrationEnterReg = "Register",
    registrationEnterTitleRules = "By clicking continue, you agree to ",
    registrationConfidentiality = "privacy policy",
    registrationAnd = " and ",
    registrationEmailPlaceholder = "mail@mail.ru",

    registrationIsErrorMaxLengthPassword = "The password must be shorter than 30 characters",
    registrationIsErrorMinLengthPassword = "Password must be longer than 6 characters",
    registrationIsErrorName = "Required field",
    registrationPasswordTitle = "Password",
    registrationConfirmPasswordTitle = "Confirm password",
    registrationEmailTitle = "Enter your Email",
    registrationServerRules = "the rules of the service",
    registrationTitleAuthorization = "Do you have an account? ",
    registrationEnterAuthorization = "Enter",
    registrationEnterWe = "\"We are very glad that you have joined us. To ensure a comfortable and productive environment for all participants, we ask you to familiarize yourself with some rules of our server:\n" +
            "\n" +
            "Prohibited: the use of foul language in the chat, posting 18+ materials, discussing politics. \uD83D\uDEAB\n" +
            "\n" +
            "This is important not only to maintain a positive emotional state of the entire community but also to prevent Discord from banning you and striking our server. \uD83D\uDE10\n" +
            "\n" +
            "Overall, we have a friendly and reasonable community where there is no hate or different \"jokes\".\n" +
            "\n" +
            "We do not welcome negativity.\n" +
            "\n" +
            "Our glass is not just always half full, it is half full of the most expensive wine, and we are ready to share it. \uD83E\uDD42\uD83D\uDE0E\n" +
            "\n" +
            "Each participant is ready to help others. \uD83D\uDEC2\n" +
            "\n" +
            "By joining our community, you take responsibility for your own education, no one will forcibly drag you. \uD83D\uDE4C\"",
    registrationPolicy = "Privacy Policy\n" +
            "\n" +
            "This privacy policy describes what data we collect, how it is used, and how we protect it in our application.\n" +
            "\n" +
            "Data collected:\n" +
            "We collect the following data from users:\n" +
            "Name and email address for registration\n" +
            "Location data when using geolocation\n" +
            "Device information (device type, operating system version, etc.)\n" +
            "Use of data:\n" +
            "The collected data is used solely for:\n" +
            "Providing users with the ability to use the application's functionality\n" +
            "Communicating with users\n" +
            "Improving the quality of services provided\n" +
            "Data protection:\n" +
            "We take measures to protect user data from unauthorized access, leaks, or loss. We do not disclose data to third parties without your consent.\n" +
            "\n" +
            "User consent:\n" +
            "By using our application, you agree to our privacy policy. If you have any questions or need additional information, please contact us.\n" +
            "\n" +
            "This privacy policy takes effect from the moment users use the application. Any changes to the policy will be posted on this page.",
    forgetPasswordTitle = "Forgot password?",
    forgetPasswordEnterYourEmail = "Enter your email",
    forgetPasswordEnterYourEmailPlaceholder = "mail@mail.ru",
    forgetPasswordDontExist = "No profile with this email exists",
    forgetPasswordSend = "Send",
    forgetPasswordEmptyError = "required field",
    forgetPasswordInvalidEmail = "Invalid email. Only numbers and Latin letters are allowed.",
    forgotSuccessSend = "The message was sent by email" +
            "\nFollow the instructions in the email to complete your account setup.",

    onboardingStart = "Start",
    onboardingNext = "Next",
    onboardingSkip = "Skip",
    onboardingScreen1Title = "Devrush Community",
    onboardingScreen1Description = "Your practical path to the world of development",
    onboardingScreen2Title = "Team",
    onboardingScreen2Description = "Learn to work in a team by participating in team development, close to commercial.",
    onboardingScreen3Title = "Portfolio",
    onboardingScreen3Description = "Complete our training programs and add at least 12 working applications to your portfolio.",
    onboardingScreen4Title = "Knowledge Base",
    onboardingScreen4Description = "In two years of our community's existence, we have gathered a large knowledge base for you to study programming.",

    quizAboutUrSelf = "Tell us about yourself",
    quizProgrammingLanguage = "Which programming language are you planning to study?",
    quizAnswerAFewQuestions = "Answer a few questions and get a BONUS at the end!",

    swift = "Swift",
    kotlin = "Kotlin",

    quizJavascript = "JavaScript",
    quizChooseFramework = "Choose a framework?",
    quizUiKit = "UIKit",
    quizNodeJs = "Node JS",
    quizReact = "React",
    quizSwiftUI = "Swift UI",
    quizContinue = "Continue",
    quizBack = "Back",
    quizHowLongLearn = "How long have you been learning this programming language?",
    quizSixMonth = "< 6 months",
    quizMoreSixMonth = "> 6 months",
    quizYear = "> 1 year",
    quizUrInterests = "Your interests",
    quizPainting = "Painting",
    quizMusic = "Music",
    quizFashion = "Fashion",
    quizCinema = "Cinema",
    quizExhibitions = "Exhibitions",
    quizArt = "Art",
    quizVocals = "Vocals",
    quizQuests = "Quests",
    quizSport = "Sports",
    quizDance = "Dance",
    quizEnd = "Finish",

    couponFully = "Cover to cover",
    couponCourse = "The course “Proust, Camus, and Sartre: how to understand French literature” suits you",
    coupon15 = "We give you a promo code with a 15% discount on this course",
    couponLucky = "Try your luck",
    couponSwipe = "Swipe to tear off the ticket",
    couponSignUp = "Sign up for the course",
    couponSkidka15 = "DISCOUNT15",

    listOfCoursesCourses = "Courses",
    listOfCoursesCat = "But there is a cute cat :)",
    listOfCoursesStartedCourses = "Started courses",
    listOfCourses = "List of courses",
    listOfCoursesNotifications = "Notifications",
    listOfCoursesMarkAll = "Mark all as read",
    listOfCoursesAccrual = "Accrual under the affiliate program",
    listOfCoursesSum = "Sum",
    listOfCoursesLink = "Link",
    listOfCoursesReferral = "Referral",

    coursesStart = "Start",
    all = "All",

    profileDescription = "Description",
    profileBestProject = "Best team project",
    profileBestProjectDescription = "The project made in the team challenge was chosen as the best among all teams",
    profileActiveAchievements = "Active achievements",
    profileAllAchievements = "All achievements",
    profileInactiveAchievements = "Inactive achievements",
    profileHero = "Cinema - Hero",
    profileMentor = "Mentor",
    profileMentorPro = "Mentor PRO",
    profileTop5 = "TOP 5",
    profileBestReport = "Best report",
    profile = "Profile",
    profileMyStatistics = "My statistics",
    profilePoints = "Points",
    profileRank = "Rank",
    profileAchievements = "Achievements",
    profileLeader = "Team leader",
    profileReporter = "Reporter",
    profileResearcher = "Student researcher",
    profileLeaderboard = "Leaderboard",
    profileFirstPlace = "1st place",
    profileSecondPlace = "2nd place",
    profileThirdPlace = "3rd place",
    profileAccessPayments = "Access and payments",
    profileSubscriptions = "Subscriptions",
    profileAccesses = "Accesses",
    profileOrders = "Orders",
    profileOrder = "Order",
    profileSettings = "Profile settings",
    profileDone = "Done",
    profileChangePhoto = "Change profile photo",
    profileAccount = "Account",
    profileEmail = "Email",
    profileName = "Name",
    profileSurname = "Surname",
    profilePatronymic = "Patronymic",
    profilePhone = "Phone",
    profileBirthDate = "Birth date",
    profileGender = "Gender",
    profileGenderFemale = "Female",
    profileGenderMale = "Male",
    profilePasswordSettings = "Password settings",
    profilePassword = "Password",
    profileConfirmPassword = "Confirm password",
    profileAppSettings = "App settings",
    profileNewsUpdatesPromotions = "News, announcements, promotions",
    profileTheme = "Theme",
    profileDarkTheme = "Dark",
    profileLightTheme = "Light",
    profileSystemTheme = "Follow system",
    profileLogout = "Logout",
    profileDeleteAccount = "Delete account",
    profileCat = "There's nothing here. But there's a cute cat ;)",
    profileCourse = "Course",
    profileLibrary = "Library",
    profileActive = "Active",
    profileExpired = "Expired",
    profileCreationDate = "Date of creation",
    profileExpires = "Expires",
    profileNotSavedProfile = "Be careful, you didn't save the changes!",
    profileRenewSubscription = "Renew subscription",
    profileCancelSubscription = "Cancel subscription",
    profileOrderAmount = "Order amount: ",
    profileDateOfDebiting = "Date of debiting: ",
    profilePayOrder = "Pay",
    profileEmptyLeaderboard = "The leaderboard is empty",
    profileAmountOfPayment = "Payment amount",
    profileCancelSubscriptionRenewal = "Cancel renewal",
    profileRenewalIsSuspended = "Renewal is suspended",
    profileConfirmSnackBar = "Passwords must match",
    profileSuccessChangeData = "Data changed successfully",
    profileSettingsPhoneTextFieldValidationError = "Enter a valid phone number",
    profileSettingsPhoneTextFieldSelectCountry = "Select country",
    profileEmptyName = "Fill in the required fields",
    profileDatePicketCancel = "Cancel",
    profileDatePickerOk = "OK",

    accessesPaymentsUnlimitedAccess = "Unlimited access",
    accessesPaymentsEmptyPlug = "There is nothing here at the moment :)",

    coursesCourses = "Courses",
    coursesStartedCourses = "Courses started",
    coursesListCourses = "List of courses",
    coursesSearch = "Search",
    coursesFilterAll = "All",

    libraryTitle = "Library",

    chatYouDeletedThisMessage = "You deleted this message",
    chatMessageRemoved = "Message removed",
    chatAnswer = "Answer",
    chatPhoto = "Photo",


    notificationStudentPartnershipRegistration = "New referral registration",
    notificationStudentPartnershipTransaction = "Accrual under the affiliate program",
    notificationPasswordChanged = "Your password has been changed. If you didn't do it, then contact technical support",
    notificationStudentBonusTransaction = "Debiting from the bonus account",
    notificationLibraryItemComment = "Comment on the library step",
    notificationStudentBonus = "Accrual to the bonus account",
    notificationDeposit = "Accrual to the bonus account",
    notificationWithdrawal = "Debiting from the bonus account",
    notificationAdminPartnershipTransactionRequest = "Withdrawal request for the affiliate program",
    notificationCourseTaskAnswerStatus = "The answer to the task",
    notificationTaskInStep = "The task in the step",
    notificationApproved = "approved in the course",
    notificationNeedAdd = "You need to add to the course",
)